#ddev-generated
# Simple template to demonstrate addon-template
services:
  orthanc:
    container_name: ddev-${DDEV_SITENAME}-orthanc
    image: osimis/orthanc
    networks: [default, ddev_default]
    ports: ["104:4242", "8042:8042"]
    restart: "no"

    environment:
      ORTHANC__NAME: ${DDEV_SITENAME}
      ORTHANC__REGISTERED_USERS: |
        {"orthanc": "orthanc"}

    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
    - ".:/mnt/ddev_config"
    - "orthanc-storage:/var/lib/orthanc/db:Z"

    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s orthanc:8042"]

volumes:
  orthanc-storage: